# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Download Hugo
        env: 
          HUGO_VERSION: 0.78.1
        run: |
          curl -LO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
          sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
      
      - name: Build Site
        run: |
          ls -ltR
          hugo

      # Runs a set of commands using the runners shell
      - name: Deploy
        run: |
          cd public

          git init
          git config --global push.default matching
          git config --global user.email "github@stomer.net"
          git config --global user.name "Github Blog"
          git add --all .
          git commit -m "Publishing to master (GH action)"
          git push --quiet --force https://paulgrav:${{ secrets.TOKEN }}@github.com/paulgrav/paulgrav.github.io.git master
